import type { Municipio, Publicacion } from "@/types/site"

export const fallbackMunicipios: Municipio[] = [
  {
    id: "charata",
    slug: "charata",
    nombre: "Charata",
    estado: "cumple",
    region: "Sudoeste",
    provincia: "Chaco",
    intendente: "Jorge Capitanich",
    poblacion: "30.000",
    ultimaActualizacion: "15 de Marzo, 2024",
    descripcion: "Municipio principal del sudoeste chaqueño.",
    indicadores: [
      { titulo: "Presupuesto publicado", cumple: true, descripcion: "Presupuesto anual 2024 disponible en el portal municipal." },
      { titulo: "Ejecución presupuestaria", cumple: true, descripcion: "Informes trimestrales actualizados hasta marzo 2024." },
      { titulo: "Ordenanzas municipales", cumple: true, descripcion: "Ordenanzas 2023-2024 publicadas." },
      { titulo: "Nómina de personal", cumple: true, descripcion: "Lista actualizada de empleados municipales disponible." },
      { titulo: "Licitaciones y contratos", cumple: true, descripcion: "Portal de contrataciones activo y actualizado." },
      { titulo: "Actas del Concejo", cumple: true, descripcion: "Actas de sesiones publicadas dentro de los 10 días." },
    ],
    ordenanzas: [
      { numero: "1234/2023", titulo: "Presupuesto Municipal 2024", fecha: "15 de Diciembre, 2023", estado: "Publicada" },
      { numero: "1100/2023", titulo: "Rendición de Cuentas Anual", fecha: "20 de Noviembre, 2023", estado: "Publicada" },
      { numero: "980/2023", titulo: "Plan de Obras Públicas 2024", fecha: "10 de Octubre, 2023", estado: "Publicada" },
    ],
    publicaciones: [
      { titulo: "Informe de Rendición de Cuentas - Charata 2024", fecha: "15 de Marzo, 2024", categoria: "Informe Municipal", slug: "informe-rendicion-charata-2024" },
      { titulo: "Análisis del presupuesto 2024", fecha: "28 de Febrero, 2024", categoria: "Análisis" },
      { titulo: "Obras públicas en ejecución", fecha: "10 de Febrero, 2024", categoria: "Seguimiento" },
    ],
  },
  {
    id: "presidencia-roque-saenz-pena",
    slug: "presidencia-roque-saenz-pena",
    nombre: "Presidencia Roque Sáenz Peña",
    estado: "parcial",
    region: "Centro",
    provincia: "Chaco",
    intendente: "Manuel Gómez",
    poblacion: "95.000",
    ultimaActualizacion: "28 de Febrero, 2024",
    descripcion: "Capital departamental y segunda ciudad más importante.",
  },
  {
    id: "general-pinedo",
    slug: "general-pinedo",
    nombre: "General Pinedo",
    estado: "no-cumple",
    region: "Sudoeste",
    provincia: "Chaco",
    intendente: "Ricardo Fernández",
    poblacion: "12.000",
    ultimaActualizacion: "10 de Febrero, 2024",
    descripcion: "Municipio agrícola del sudoeste chaqueño.",
  },
  {
    id: "villa-angela",
    slug: "villa-angela",
    nombre: "Villa Ángela",
    estado: "parcial",
    region: "Centro",
    provincia: "Chaco",
    intendente: "María González",
    poblacion: "42.000",
    ultimaActualizacion: "5 de Marzo, 2024",
    descripcion: "Importante centro comercial de la región.",
  },
  {
    id: "las-brenas",
    slug: "las-brenas",
    nombre: "Las Breñas",
    estado: "cumple",
    region: "Sudoeste",
    provincia: "Chaco",
    intendente: "Carlos Martínez",
    poblacion: "25.000",
    ultimaActualizacion: "20 de Marzo, 2024",
    descripcion: "Centro agroindustrial del sudoeste.",
  },
  {
    id: "quitilipi",
    slug: "quitilipi",
    nombre: "Quitilipi",
    estado: "no-cumple",
    region: "Centro",
    provincia: "Chaco",
    intendente: "Ana Rodríguez",
    poblacion: "18.000",
    ultimaActualizacion: "1 de Marzo, 2024",
    descripcion: "Municipio con fuerte actividad agropecuaria.",
  },
]

export const fallbackPublicaciones: Publicacion[] = [
  {
    id: "informe-rendicion-charata-2024",
    slug: "informe-rendicion-charata-2024",
    titulo: "Informe de Rendición de Cuentas - Charata 2024",
    extracto: "Análisis completo del cumplimiento de las obligaciones de transparencia del municipio de Charata durante el primer trimestre de 2024.",
    fecha: "15 de Marzo, 2024",
    categoria: "Informe Municipal",
    municipio: "Charata",
    autor: "Equipo Transparencia Chaco",
    imagen: "/city-hall-report.jpg",
    contenido: "<h2>Resumen Ejecutivo</h2><p>El presente informe analiza el cumplimiento de las obligaciones de transparencia del municipio de Charata durante el primer trimestre de 2024.</p><h2>Conclusión</h2><p>Charata se posiciona como un ejemplo de buenas prácticas en transparencia municipal en la región.</p>",
    relacionadas: [
      { titulo: "Análisis del cumplimiento del Art. 67", slug: "analisis-art67-sudoeste-chaco", categoria: "Marco Legal" },
      { titulo: "Transparencia en fondos públicos", slug: "transparencia-fondos-publicos", categoria: "Investigación" },
    ],
  },
  {
    id: "analisis-art67-sudoeste-chaco",
    slug: "analisis-art67-sudoeste-chaco",
    titulo: "Análisis del cumplimiento del Art. 67 en el sudoeste chaqueño",
    extracto: "Estudio comparativo sobre el cumplimiento del Artículo 67 de la Ley Orgánica de Municipios en seis municipios de la región.",
    fecha: "28 de Febrero, 2024",
    categoria: "Marco Legal",
    municipio: "Varios",
    autor: "María González",
    imagen: "/legal-documents-argentina.jpg",
    contenido: "<p>Estudio comparativo del cumplimiento legal de la rendición de cuentas en municipios del sudoeste chaqueño.</p>",
  },
  {
    id: "transparencia-fondos-publicos",
    slug: "transparencia-fondos-publicos",
    titulo: "Transparencia en el uso de fondos públicos municipales",
    extracto: "Investigación sobre la publicación de información presupuestaria y su ejecución en municipios chaqueños.",
    fecha: "10 de Febrero, 2024",
    categoria: "Investigación",
    municipio: "Varios",
    autor: "Carlos Martínez",
    imagen: "/public-budget-transparency.jpg",
    contenido: "<p>Relevamiento sobre publicación y acceso a la información presupuestaria municipal.</p>",
  },
  {
    id: "obras-publicas-general-pinedo",
    slug: "obras-publicas-general-pinedo",
    titulo: "Estado de obras públicas en General Pinedo",
    extracto: "Relevamiento de obras públicas anunciadas y su estado real de avance en el municipio de General Pinedo.",
    fecha: "5 de Febrero, 2024",
    categoria: "Seguimiento",
    municipio: "General Pinedo",
    autor: "Ana Rodríguez",
    imagen: "/public-construction-works.jpg",
    contenido: "<p>Informe de seguimiento del estado de obras públicas anunciadas.</p>",
  },
  {
    id: "mejores-practicas-portales-transparencia",
    slug: "mejores-practicas-portales-transparencia",
    titulo: "Portal de transparencia: mejores prácticas municipales",
    extracto: "Análisis de los portales de transparencia más efectivos y recomendaciones para municipios del Chaco.",
    fecha: "28 de Enero, 2024",
    categoria: "Análisis",
    municipio: "Varios",
    autor: "Equipo Transparencia Chaco",
    imagen: "/web-portal-transparency.jpg",
    contenido: "<p>Buenas prácticas y recomendaciones para fortalecer portales municipales de transparencia.</p>",
  },
  {
    id: "presupuesto-participativo-las-brenas",
    slug: "presupuesto-participativo-las-brenas",
    titulo: "Presupuesto participativo en Las Breñas",
    extracto: "Caso de éxito: cómo Las Breñas implementó un sistema de presupuesto participativo con amplia participación ciudadana.",
    fecha: "15 de Enero, 2024",
    categoria: "Caso de Éxito",
    municipio: "Las Breñas",
    autor: "Roberto Fernández",
    imagen: "/participatory-budget-meeting.jpg",
    contenido: "<p>Experiencia de participación ciudadana aplicada al presupuesto municipal.</p>",
  },
]

export function getFallbackMunicipioBySlug(slug: string) {
  return fallbackMunicipios.find((municipio) => municipio.slug === slug) ?? null
}

export function getFallbackPublicacionBySlug(slug: string) {
  return fallbackPublicaciones.find((publicacion) => publicacion.slug === slug) ?? null
}
