// Fallback data — SOLO para desarrollo local. No usar con Firestore.
import type { ObraPublica } from "@/types/obras"

export const fallbackObras: ObraPublica[] = [
  {
    id: "obra-1",
    municipio: "Charata",
    municipioSlug: "charata",
    nombre: "Pavimentación Calle San Martín tramo Norte",
    descripcion:
      "Pavimentación asfáltica de cuatro cuadras sobre calle San Martín entre Av. Independencia y calle Belgrano, incluyendo cordón cuneta y repavimentación de intersecciones.",
    ubicacionTexto: "Calle San Martín entre Av. Independencia y calle Belgrano, Charata",
    tipo: "pavimento",
    origenFondos: "municipal",
    ejecucion: "administracion-propia",
    responsableInformado: "Secretaría de Obras Públicas Municipal",
    presupuestoInformado: "$18.500.000",
    fechaAnuncioISO: "2023-11-15",
    fechaInicioISO: "2024-02-01",
    fechaFinISO: "2024-06-30",
    estado: "finalizada",
    avancePorcentaje: 100,
    fuenteInformacion: "Comunicado oficial Municipalidad de Charata, junio 2024",
    nivelVerificacion: 2,
    visibilidadPublica: true,
    estadoEditorial: "published",
    createdAt: "2024-07-01",
    updatedAt: "2024-07-01",
  },
  {
    id: "obra-2",
    municipio: "Charata",
    municipioSlug: "charata",
    nombre: "Red cloacal barrio Los Lapachos",
    descripcion:
      "Extensión de la red de cloacas hacia el barrio Los Lapachos, contemplando colectoras secundarias, cámaras de inspección y conexiones domiciliarias para aproximadamente 180 viviendas.",
    ubicacionTexto: "Barrio Los Lapachos, Charata",
    tipo: "cloacas",
    origenFondos: "provincial",
    ejecucion: "empresa-contratista",
    contratista: "Constructora Chaco Norte S.R.L.",
    presupuestoInformado: "$62.000.000",
    fechaAnuncioISO: "2024-01-20",
    fechaInicioISO: "2024-03-10",
    estado: "en-ejecucion",
    avancePorcentaje: 45,
    fuenteInformacion: "Licitación pública N° 004/2024, Municipalidad de Charata",
    nivelVerificacion: 2,
    visibilidadPublica: true,
    estadoEditorial: "published",
    createdAt: "2024-07-15",
    updatedAt: "2024-07-15",
  },
  {
    id: "obra-3",
    municipio: "Las Breñas",
    municipioSlug: "las-brenas",
    nombre: "Iluminación LED Av. General Güemes",
    descripcion:
      "Reemplazo del alumbrado público existente por luminarias LED de alta eficiencia en la Avenida General Güemes. La obra fue adjudicada pero se detuvo por conflicto contractual con la empresa adjudicataria.",
    ubicacionTexto: "Av. General Güemes, Las Breñas",
    tipo: "iluminacion",
    origenFondos: "municipal",
    ejecucion: "empresa-contratista",
    contratista: "Electro Sur S.A.",
    presupuestoInformado: "$9.200.000",
    fechaAnuncioISO: "2023-09-05",
    fechaInicioISO: "2023-12-01",
    estado: "paralizada",
    avancePorcentaje: 20,
    fuenteInformacion: "Pedido de informe concejal N° 12/2024, Las Breñas",
    pedidoInformeAsociado: true,
    nivelVerificacion: 1,
    visibilidadPublica: true,
    estadoEditorial: "published",
    createdAt: "2024-07-20",
    updatedAt: "2024-07-20",
  },
  {
    id: "obra-4",
    municipio: "Las Breñas",
    municipioSlug: "las-brenas",
    nombre: "Refuncionalización Plaza Central",
    descripcion:
      "Proyecto anunciado para la renovación integral de la plaza central, incluyendo senderos, mobiliario urbano, juegos infantiles y nueva forestación. Sin fecha de inicio confirmada.",
    ubicacionTexto: "Plaza Central, Las Breñas",
    tipo: "plaza",
    origenFondos: "municipal",
    ejecucion: "desconocido",
    fechaAnuncioISO: "2024-05-10",
    estado: "anunciada",
    fuenteInformacion: "Declaración del intendente, mayo 2024",
    nivelVerificacion: 1,
    visibilidadPublica: true,
    estadoEditorial: "published",
    createdAt: "2024-07-22",
    updatedAt: "2024-07-22",
  },
  {
    id: "obra-5",
    municipio: "Corzuela",
    municipioSlug: "corzuela",
    nombre: "Ampliación edificio Centro de Salud",
    descripcion:
      "Se registra la existencia de un proyecto de ampliación del Centro de Salud municipal, pero no se cuenta con información verificable sobre estado, presupuesto ni cronograma.",
    ubicacionTexto: "Centro de Salud Municipal, Corzuela",
    tipo: "edificio-publico",
    origenFondos: "desconocido",
    ejecucion: "desconocido",
    estado: "sin-informacion",
    nivelVerificacion: 1,
    visibilidadPublica: true,
    estadoEditorial: "published",
    createdAt: "2024-07-25",
    updatedAt: "2024-07-25",
  },
  {
    id: "obra-6",
    municipio: "Presidencia Roque Sáenz Peña",
    municipioSlug: "presidencia-roque-saenz-pena",
    nombre: "Canal de desagüe pluvial sector sudeste",
    descripcion:
      "Construcción de canal de desagüe pluvial para mitigar inundaciones en el sector sudeste de la ciudad, ejecutado por la Dirección Provincial de Recursos Hídricos del Chaco.",
    ubicacionTexto: "Sector sudeste, Presidencia Roque Sáenz Peña",
    tipo: "obra-hidraulica",
    origenFondos: "provincial",
    ejecucion: "ejecucion-provincial",
    responsableInformado: "Dirección Provincial de Recursos Hídricos — Chaco",
    presupuestoInformado: "$45.000.000",
    fechaAnuncioISO: "2023-06-01",
    fechaInicioISO: "2023-08-15",
    fechaFinISO: "2024-04-30",
    estado: "finalizada",
    avancePorcentaje: 100,
    fuenteInformacion: "Comunicado oficial Ministerio de Infraestructura del Chaco, mayo 2024",
    nivelVerificacion: 2,
    visibilidadPublica: true,
    estadoEditorial: "published",
    createdAt: "2024-07-28",
    updatedAt: "2024-07-28",
  },
]
