// Fallback data — SOLO para desarrollo local cuando Firebase no está configurado
import type { ReporteAccidente, ReporteCiudadano, ReporteSalud } from "@/types/reportes"

export const fallbackReportes: ReporteCiudadano[] = [
  {
    id: "fallback-reporte-1",
    municipio: "Charata",
    municipioSlug: "charata",
    tipo: "bache",
    titulo: "Bache peligroso en Av. San Martín",
    descripcion:
      "Gran bache en el cruce de Av. San Martín y calle 25 de Mayo. Afecta el tránsito vehicular y representa un riesgo para motos.",
    fechaHechoISO: "2025-05-10",
    ubicacionTexto: "Av. San Martín y 25 de Mayo, Charata",
    anonimo: true,
    estadoInterno: "publicado",
    nivelVerificacion: 1,
    visibilidadPublica: true,
    createdAt: "2025-05-11",
  },
  {
    id: "fallback-reporte-2",
    municipio: "Charata",
    municipioSlug: "charata",
    tipo: "iluminacion",
    titulo: "Luminarias apagadas en Barrio Norte",
    descripcion:
      "Más de seis luminarias sin funcionar en Barrio Norte desde hace tres semanas. La zona queda completamente oscura de noche.",
    fechaHechoISO: "2025-05-01",
    ubicacionTexto: "Barrio Norte, Charata",
    anonimo: true,
    estadoInterno: "publicado",
    nivelVerificacion: 1,
    visibilidadPublica: true,
    createdAt: "2025-05-05",
  },
  {
    id: "fallback-reporte-3",
    municipio: "Las Breñas",
    municipioSlug: "las-brenas",
    tipo: "obra-publica",
    titulo: "Obra de pavimentación sin terminar",
    descripcion:
      "La obra de pavimentación en calle Corrientes lleva más de cuatro meses paralizada. No hay señalización adecuada y dificulta el tránsito.",
    fechaHechoISO: "2025-04-20",
    ubicacionTexto: "Calle Corrientes entre Sarmiento y Belgrano, Las Breñas",
    anonimo: true,
    estadoInterno: "publicado",
    nivelVerificacion: 1,
    visibilidadPublica: true,
    createdAt: "2025-04-22",
  },
  {
    id: "fallback-reporte-4",
    municipio: "Las Breñas",
    municipioSlug: "las-brenas",
    tipo: "inseguridad",
    titulo: "Zona sin patrullaje nocturno",
    descripcion:
      "Vecinos de calle Rivadavia reportan ausencia de patrullaje policial en horario nocturno. Hubo varios incidentes menores en el mes.",
    fechaHechoISO: "2025-05-08",
    ubicacionTexto: "Calle Rivadavia, Las Breñas",
    anonimo: true,
    estadoInterno: "publicado",
    nivelVerificacion: 1,
    visibilidadPublica: true,
    createdAt: "2025-05-09",
  },
  {
    id: "fallback-reporte-5",
    municipio: "Corzuela",
    municipioSlug: "corzuela",
    tipo: "calle",
    titulo: "Calle de tierra intransitable tras lluvias",
    descripcion:
      "La calle Vélez Sársfield en el sector sur queda completamente intransitable tras las lluvias. Vecinos solicitan ripiado o pavimento.",
    fechaHechoISO: "2025-05-12",
    ubicacionTexto: "Calle Vélez Sársfield, sector sur, Corzuela",
    anonimo: true,
    estadoInterno: "publicado",
    nivelVerificacion: 1,
    visibilidadPublica: true,
    createdAt: "2025-05-13",
  },
  {
    id: "fallback-reporte-6",
    municipio: "Presidencia Roque Sáenz Peña",
    municipioSlug: "presidencia-roque-saenz-pena",
    tipo: "otro",
    titulo: "Contenedores de basura desbordados hace días",
    descripcion:
      "Los contenedores en la Plaza Central llevan varios días sin recolección. El olor y la presencia de animales generan malestar entre los vecinos.",
    fechaHechoISO: "2025-05-14",
    ubicacionTexto: "Plaza Central, Presidencia Roque Sáenz Peña",
    anonimo: true,
    estadoInterno: "publicado",
    nivelVerificacion: 1,
    visibilidadPublica: true,
    createdAt: "2025-05-15",
  },
]

export const fallbackAccidentes: ReporteAccidente[] = [
  {
    id: "fallback-accidente-1",
    municipio: "Charata",
    municipioSlug: "charata",
    tipo: "accidente",
    titulo: "Choque en intersección sin señalización",
    descripcion:
      "Colisión entre dos vehículos en cruce sin semáforo ni señal de pare. Los conductores resultaron ilesos pero uno de los vehículos tuvo daños materiales.",
    fechaHechoISO: "2025-05-09",
    ubicacionTexto: "Av. Belgrano e Independencia, Charata",
    anonimo: true,
    estadoInterno: "publicado",
    nivelVerificacion: 1,
    visibilidadPublica: true,
    createdAt: "2025-05-09",
    subtipo: "transito",
    gravedad: "baja",
    huboDenunciaPolicial: "si",
    huboIntervencionMunicipal: "no",
  },
  {
    id: "fallback-accidente-2",
    municipio: "Las Breñas",
    municipioSlug: "las-brenas",
    tipo: "inseguridad",
    titulo: "Robo domiciliario en zona residencial",
    descripcion:
      "Ingreso forzado a vivienda del barrio sur durante horas de la mañana. Se llevaron electrónica y efectivo. Los vecinos piden mayor patrullaje.",
    fechaHechoISO: "2025-05-07",
    ubicacionTexto: "Barrio Sur, Las Breñas",
    anonimo: true,
    estadoInterno: "publicado",
    nivelVerificacion: 1,
    visibilidadPublica: true,
    createdAt: "2025-05-08",
    subtipo: "robo-domiciliario",
    gravedad: "media",
    huboDenunciaPolicial: "si",
    huboIntervencionMunicipal: "no",
  },
  {
    id: "fallback-accidente-3",
    municipio: "Corzuela",
    municipioSlug: "corzuela",
    tipo: "inseguridad",
    titulo: "Zona peligrosa por falta de iluminación y baldíos",
    descripcion:
      "Sector entre calle Moreno y el acceso sur identificado por vecinos como zona de riesgo por baldíos, oscuridad y falta de control.",
    fechaHechoISO: "2025-04-30",
    ubicacionTexto: "Entre Moreno y acceso sur, Corzuela",
    anonimo: true,
    estadoInterno: "publicado",
    nivelVerificacion: 1,
    visibilidadPublica: true,
    createdAt: "2025-05-01",
    subtipo: "zona-peligrosa",
    gravedad: "baja",
    huboDenunciaPolicial: "no",
    huboIntervencionMunicipal: "no",
  },
  {
    id: "fallback-accidente-4",
    municipio: "Presidencia Roque Sáenz Peña",
    municipioSlug: "presidencia-roque-saenz-pena",
    tipo: "accidente",
    titulo: "Accidente grave en ruta de acceso",
    descripcion:
      "Vuelco de camioneta en el acceso norte a la ciudad. Una persona resultó herida de gravedad y fue trasladada al hospital local.",
    fechaHechoISO: "2025-05-11",
    ubicacionTexto: "Acceso norte, Presidencia Roque Sáenz Peña",
    anonimo: true,
    estadoInterno: "publicado",
    nivelVerificacion: 1,
    visibilidadPublica: true,
    createdAt: "2025-05-11",
    subtipo: "transito",
    gravedad: "alta",
    huboDenunciaPolicial: "si",
    huboIntervencionMunicipal: "si",
  },
]

export const fallbackReportesSalud: ReporteSalud[] = [
  {
    id: "fallback-salud-1",
    municipio: "Charata",
    municipioSlug: "charata",
    tipo: "hospital",
    titulo: "Falta de médicos de guardia en el hospital local",
    descripcion:
      "Pacientes denuncian que el hospital municipal no tiene médico de guardia durante los fines de semana. Los turnos de guardia no se cubren regularmente.",
    fechaHechoISO: "2025-05-10",
    ubicacionTexto: "Hospital Municipal, Charata",
    anonimo: true,
    estadoInterno: "publicado",
    nivelVerificacion: 1,
    visibilidadPublica: true,
    createdAt: "2025-05-12",
    hospital: "Hospital Municipal de Charata",
    tipoProblema: "falta-medicos",
    hizoReclamoFormal: false,
    recibioRespuesta: false,
  },
  {
    id: "fallback-salud-2",
    municipio: "Las Breñas",
    municipioSlug: "las-brenas",
    tipo: "hospital",
    titulo: "Sin insumos básicos en sala de urgencias",
    descripcion:
      "La sala de urgencias del hospital de Las Breñas no cuenta con gasas, suero ni guantes en cantidad suficiente. Los propios pacientes deben traer insumos.",
    fechaHechoISO: "2025-05-06",
    ubicacionTexto: "Hospital de Las Breñas",
    anonimo: true,
    estadoInterno: "publicado",
    nivelVerificacion: 1,
    visibilidadPublica: true,
    createdAt: "2025-05-07",
    hospital: "Hospital de Las Breñas",
    tipoProblema: "falta-insumos",
    hizoReclamoFormal: false,
    recibioRespuesta: false,
  },
  {
    id: "fallback-salud-3",
    municipio: "Corzuela",
    municipioSlug: "corzuela",
    tipo: "hospital",
    titulo: "Demoras de más de cinco horas en la guardia",
    descripcion:
      "Pacientes en estado no crítico esperan más de cinco horas para ser atendidos en la guardia. Se hizo reclamo formal ante la dirección del hospital.",
    fechaHechoISO: "2025-05-03",
    ubicacionTexto: "Hospital de Corzuela",
    anonimo: true,
    estadoInterno: "publicado",
    nivelVerificacion: 1,
    visibilidadPublica: true,
    createdAt: "2025-05-04",
    hospital: "Hospital de Corzuela",
    tipoProblema: "demoras",
    hizoReclamoFormal: true,
    recibioRespuesta: false,
  },
  {
    id: "fallback-salud-4",
    municipio: "Presidencia Roque Sáenz Peña",
    municipioSlug: "presidencia-roque-saenz-pena",
    tipo: "hospital",
    titulo: "Ambulancia sin combustible durante emergencia",
    descripcion:
      "Una ambulancia del sistema de emergencias no pudo trasladar a un paciente por falta de combustible. El traslado se realizó con demora en vehículo particular.",
    fechaHechoISO: "2025-05-08",
    ubicacionTexto: "Presidencia Roque Sáenz Peña",
    anonimo: true,
    estadoInterno: "publicado",
    nivelVerificacion: 1,
    visibilidadPublica: true,
    createdAt: "2025-05-09",
    hospital: "Sistema de Emergencias Municipal",
    tipoProblema: "ambulancia",
    hizoReclamoFormal: false,
    recibioRespuesta: false,
  },
]
