// Fallback data — uso local únicamente (desarrollo sin Firebase configurado)
import type { Medio, PautaOficial, PedidoInformacion, ProveedorEstado, RankingMunicipio } from "@/types/transparencia"

export const fallbackPedidos: PedidoInformacion[] = [
  {
    id: "pedido-001",
    fechaISO: "2024-03-10",
    organismo: "Municipalidad de Charata",
    municipio: "Charata",
    municipioSlug: "charata",
    tema: "Listado obras 2024",
    textoPedido: "Solicito el listado completo de obras públicas ejecutadas o en ejecución durante el año 2024.",
    estado: "sin-respuesta",
    nivelVerificacion: 2,
    visibilidadPublica: true,
    estadoEditorial: "published",
    createdAt: "2024-03-10T10:00:00.000Z",
  },
  {
    id: "pedido-002",
    fechaISO: "2025-01-15",
    organismo: "Municipalidad de Las Breñas",
    municipio: "Las Breñas",
    municipioSlug: "las-brenas",
    tema: "Presupuesto municipal 2025",
    textoPedido: "Solicito el presupuesto municipal aprobado para el ejercicio 2025 con detalle por área.",
    estado: "respondido-parcial",
    fechaRespuestaISO: "2025-02-03",
    respuestaResumen: "Se entregó el presupuesto consolidado pero sin el detalle por área solicitado.",
    nivelVerificacion: 3,
    visibilidadPublica: true,
    estadoEditorial: "published",
    createdAt: "2025-01-15T09:00:00.000Z",
  },
  {
    id: "pedido-003",
    fechaISO: "2024-06-01",
    organismo: "Municipalidad de Corzuela",
    municipio: "Corzuela",
    municipioSlug: "corzuela",
    tema: "Contratos de recolección",
    textoPedido: "Solicito copia de los contratos vigentes para el servicio de recolección de residuos.",
    estado: "vencido",
    nivelVerificacion: 1,
    visibilidadPublica: true,
    estadoEditorial: "published",
    createdAt: "2024-06-01T08:30:00.000Z",
  },
  {
    id: "pedido-004",
    fechaISO: "2025-03-05",
    organismo: "Municipalidad de Presidencia Roque Sáenz Peña",
    municipio: "Presidencia Roque Sáenz Peña",
    municipioSlug: "presidencia-roque-saenz-pena",
    tema: "Nómina de personal",
    textoPedido: "Solicito la nómina completa de personal municipal con cargos y remuneraciones brutas.",
    estado: "respondido-completo",
    fechaRespuestaISO: "2025-03-20",
    respuestaResumen: "Se entregó la nómina completa de personal con cargos y escalas salariales.",
    documentosPublicos: ["nomina-personal-saenz-pena-2025.pdf"],
    nivelVerificacion: 4,
    visibilidadPublica: true,
    estadoEditorial: "published",
    createdAt: "2025-03-05T11:00:00.000Z",
  },
  {
    id: "pedido-005",
    fechaISO: "2026-04-02",
    organismo: "Municipalidad de Charata",
    municipio: "Charata",
    municipioSlug: "charata",
    tema: "Ejecución presupuestaria Q1 2026",
    textoPedido: "Solicito el informe de ejecución presupuestaria correspondiente al primer trimestre de 2026.",
    estado: "en-plazo",
    nivelVerificacion: 2,
    visibilidadPublica: true,
    estadoEditorial: "published",
    createdAt: "2026-04-02T09:15:00.000Z",
  },
  {
    id: "pedido-006",
    fechaISO: "2025-11-20",
    organismo: "Municipalidad de Las Breñas",
    municipio: "Las Breñas",
    municipioSlug: "las-brenas",
    tema: "Contratistas de obras",
    textoPedido: "Solicito el listado de empresas contratistas que ejecutaron obras durante 2025.",
    estado: "sin-respuesta",
    nivelVerificacion: 2,
    visibilidadPublica: true,
    estadoEditorial: "published",
    createdAt: "2025-11-20T10:45:00.000Z",
  },
]

export const fallbackMedios: Medio[] = [
  {
    id: "medio-001",
    nombre: "Portal Charatense",
    ciudadPrincipal: "Charata",
    ciudadSlug: "charata",
    tipo: "portal-web",
    sitioWeb: "https://portalcharatense.com.ar",
    descripcion: "Portal de noticias locales de Charata y zona de influencia.",
    estado: "activo",
    recibePautaOficial: true,
    indiceTransparencia: 45,
    semaforo: "amarillo",
    visibilidadPublica: true,
    estadoEditorial: "published",
    createdAt: "2024-01-10T00:00:00.000Z",
  },
  {
    id: "medio-002",
    nombre: "Radio Las Breñas",
    ciudadPrincipal: "Las Breñas",
    ciudadSlug: "las-brenas",
    tipo: "radio",
    descripcion: "Emisora de radiodifusión AM/FM con cobertura en el oeste chaqueño.",
    estado: "activo",
    recibePautaOficial: true,
    indiceTransparencia: 72,
    semaforo: "verde",
    visibilidadPublica: true,
    estadoEditorial: "published",
    createdAt: "2024-01-10T00:00:00.000Z",
  },
  {
    id: "medio-003",
    nombre: "Info Corzuela",
    ciudadPrincipal: "Corzuela",
    ciudadSlug: "corzuela",
    tipo: "portal-web",
    descripcion: "Sitio de noticias locales de Corzuela.",
    estado: "sin-verificar",
    recibePautaOficial: false,
    indiceTransparencia: 10,
    semaforo: "gris",
    visibilidadPublica: true,
    estadoEditorial: "published",
    createdAt: "2024-01-10T00:00:00.000Z",
  },
  {
    id: "medio-004",
    nombre: "Diario del Norte",
    ciudadPrincipal: "Presidencia Roque Sáenz Peña",
    ciudadSlug: "presidencia-roque-saenz-pena",
    tipo: "portal-web",
    sitioWeb: "https://diariodelnorte.com.ar",
    descripcion: "Diario digital de referencia del norte chaqueño.",
    estado: "activo",
    recibePautaOficial: true,
    indiceTransparencia: 50,
    semaforo: "amarillo",
    visibilidadPublica: true,
    estadoEditorial: "published",
    createdAt: "2024-01-10T00:00:00.000Z",
  },
]

export const fallbackPautas: PautaOficial[] = [
  {
    id: "pauta-001",
    medioId: "medio-001",
    medioNombre: "Portal Charatense",
    organismo: "Municipalidad de Charata",
    municipio: "Charata",
    municipioSlug: "charata",
    periodo: "2025-01",
    monto: "$150.000",
    concepto: "Difusión de actividades municipales",
    numeroDocumento: "RES-2025-0042",
    fuenteDocumental: "Resolución Municipal N° 42/2025",
    estadoVerificacion: "con-documento",
    visibilidadPublica: true,
    estadoEditorial: "published",
    createdAt: "2025-01-31T00:00:00.000Z",
  },
  {
    id: "pauta-002",
    medioId: "medio-002",
    medioNombre: "Radio Las Breñas",
    organismo: "Municipalidad de Las Breñas",
    municipio: "Las Breñas",
    municipioSlug: "las-brenas",
    periodo: "2025-02",
    monto: "$200.000",
    concepto: "Publicidad institucional – Carnaval 2025",
    numeroDocumento: "OP-2025-0017",
    fuenteDocumental: "Orden de Pago N° 17/2025",
    estadoVerificacion: "confirmado",
    visibilidadPublica: true,
    estadoEditorial: "published",
    createdAt: "2025-02-28T00:00:00.000Z",
  },
  {
    id: "pauta-003",
    medioId: "medio-004",
    medioNombre: "Diario del Norte",
    organismo: "Municipalidad de Presidencia Roque Sáenz Peña",
    municipio: "Presidencia Roque Sáenz Peña",
    municipioSlug: "presidencia-roque-saenz-pena",
    periodo: "2025-03",
    monto: "$320.000",
    concepto: "Difusión de licitaciones y actos de gobierno",
    numeroDocumento: "RES-2025-0115",
    fuenteDocumental: "Resolución Municipal N° 115/2025",
    estadoVerificacion: "confirmado",
    visibilidadPublica: true,
    estadoEditorial: "published",
    createdAt: "2025-03-31T00:00:00.000Z",
  },
  {
    id: "pauta-004",
    medioId: "medio-003",
    medioNombre: "Info Corzuela",
    organismo: "Municipalidad de Corzuela",
    municipio: "Corzuela",
    municipioSlug: "corzuela",
    periodo: "2024-12",
    monto: "$80.000",
    concepto: "Publicidad institucional fin de año",
    estadoVerificacion: "con-documento",
    visibilidadPublica: true,
    estadoEditorial: "published",
    createdAt: "2024-12-31T00:00:00.000Z",
  },
]

export const fallbackProveedores: ProveedorEstado[] = [
  {
    id: "proveedor-001",
    nombre: "Constructora Chaco Norte S.R.L.",
    rubro: "Construcción",
    ciudad: "Charata",
    ciudadSlug: "charata",
    organismoContratante: "Municipalidad de Charata",
    tipoContratacion: "licitacion",
    objeto: "Pavimentación calle Rivadavia tramo Norte",
    monto: "$4.500.000",
    periodo: "2024-2025",
    fuenteDocumental: "Licitación Pública N° 03/2024",
    estadoCumplimiento: "en-ejecucion",
    semaforo: "amarillo",
    visibilidadPublica: true,
    estadoEditorial: "published",
    createdAt: "2024-05-01T00:00:00.000Z",
  },
  {
    id: "proveedor-002",
    nombre: "Servicios Ambientales del Chaco S.A.",
    rubro: "Servicios",
    ciudad: "Charata",
    ciudadSlug: "charata",
    organismoContratante: "Municipalidad de Charata",
    tipoContratacion: "contratacion-directa",
    objeto: "Recolección diferenciada de residuos sólidos urbanos",
    monto: "$900.000",
    periodo: "2025",
    fuenteDocumental: "Contratación Directa N° 11/2025",
    estadoCumplimiento: "cumplido",
    semaforo: "verde",
    visibilidadPublica: true,
    estadoEditorial: "published",
    createdAt: "2025-01-15T00:00:00.000Z",
  },
  {
    id: "proveedor-003",
    nombre: "Agencia Creativa Norteña",
    rubro: "Publicidad",
    ciudad: "Presidencia Roque Sáenz Peña",
    ciudadSlug: "presidencia-roque-saenz-pena",
    organismoContratante: "Municipalidad de Presidencia Roque Sáenz Peña",
    tipoContratacion: "contratacion-directa",
    objeto: "Campaña de comunicación institucional 2025",
    monto: "$750.000",
    periodo: "2025",
    fuenteDocumental: "Contratación Directa N° 07/2025",
    estadoCumplimiento: "en-ejecucion",
    semaforo: "amarillo",
    visibilidadPublica: true,
    estadoEditorial: "published",
    createdAt: "2025-02-01T00:00:00.000Z",
  },
  {
    id: "proveedor-004",
    nombre: "Limpiezas Integradas S.R.L.",
    rubro: "Limpieza",
    ciudad: "Presidencia Roque Sáenz Peña",
    ciudadSlug: "presidencia-roque-saenz-pena",
    organismoContratante: "Municipalidad de Presidencia Roque Sáenz Peña",
    tipoContratacion: "licitacion",
    objeto: "Servicio de limpieza de edificios municipales",
    monto: "$1.200.000",
    periodo: "2025",
    fuenteDocumental: "Licitación Privada N° 02/2025",
    estadoCumplimiento: "cumplido",
    semaforo: "verde",
    visibilidadPublica: true,
    estadoEditorial: "published",
    createdAt: "2025-01-10T00:00:00.000Z",
  },
  {
    id: "proveedor-005",
    nombre: "TechSoluciones Chaco",
    rubro: "Tecnología",
    ciudad: "Las Breñas",
    ciudadSlug: "las-brenas",
    organismoContratante: "Municipalidad de Las Breñas",
    tipoContratacion: "contratacion-directa",
    objeto: "Provisión e instalación de sistema de gestión de reclamos ciudadanos",
    monto: "$380.000",
    periodo: "2025",
    fuenteDocumental: "Contratación Directa N° 05/2025",
    estadoCumplimiento: "sin-evaluar",
    semaforo: "gris",
    visibilidadPublica: true,
    estadoEditorial: "published",
    createdAt: "2025-03-01T00:00:00.000Z",
  },
  {
    id: "proveedor-006",
    nombre: "Vial Corzuela S.A.",
    rubro: "Construcción",
    ciudad: "Corzuela",
    ciudadSlug: "corzuela",
    organismoContratante: "Municipalidad de Corzuela",
    tipoContratacion: "licitacion",
    objeto: "Construcción de cordón cuneta barrio San Martín",
    monto: "$2.100.000",
    periodo: "2024",
    fuenteDocumental: "Licitación Pública N° 01/2024",
    estadoCumplimiento: "observado",
    semaforo: "rojo",
    visibilidadPublica: true,
    estadoEditorial: "published",
    createdAt: "2024-04-15T00:00:00.000Z",
  },
]

export const fallbackRanking: RankingMunicipio[] = [
  {
    // 20+20+15 = 55: publicaListadoObras+publicaPresupuesto+publicaContratistas
    municipio: "Presidencia Roque Sáenz Peña",
    municipioSlug: "presidencia-roque-saenz-pena",
    puntajeTotal: 55,
    criterios: {
      publicaListadoObras: true,
      publicaPresupuesto: true,
      publicaContratistas: true,
      publicaAvanceFisico: false,
      publicaFechas: false,
      respondePedidos: false,
      publicaDocumentos: false,
    },
    obrasRegistradas: 14,
    obrasParalizadas: 1,
    accidentesReportados: 0,
    reclamosSalud: 3,
    pedidosSinRespuesta: 2,
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  {
    // 20+20 = 40: publicaListadoObras+publicaPresupuesto
    municipio: "Las Breñas",
    municipioSlug: "las-brenas",
    puntajeTotal: 40,
    criterios: {
      publicaListadoObras: true,
      publicaPresupuesto: true,
      publicaContratistas: false,
      publicaAvanceFisico: false,
      publicaFechas: false,
      respondePedidos: false,
      publicaDocumentos: false,
    },
    obrasRegistradas: 8,
    obrasParalizadas: 2,
    accidentesReportados: 1,
    reclamosSalud: 1,
    pedidosSinRespuesta: 4,
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  {
    // 20+15 = 35: publicaPresupuesto+publicaAvanceFisico
    municipio: "Charata",
    municipioSlug: "charata",
    puntajeTotal: 35,
    criterios: {
      publicaListadoObras: false,
      publicaPresupuesto: true,
      publicaContratistas: false,
      publicaAvanceFisico: true,
      publicaFechas: false,
      respondePedidos: false,
      publicaDocumentos: false,
    },
    obrasRegistradas: 6,
    obrasParalizadas: 3,
    accidentesReportados: 2,
    reclamosSalud: 5,
    pedidosSinRespuesta: 6,
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  {
    // 10+10 = 20: publicaFechas+respondePedidos
    municipio: "Corzuela",
    municipioSlug: "corzuela",
    puntajeTotal: 20,
    criterios: {
      publicaListadoObras: false,
      publicaPresupuesto: false,
      publicaContratistas: false,
      publicaAvanceFisico: false,
      publicaFechas: true,
      respondePedidos: true,
      publicaDocumentos: false,
    },
    obrasRegistradas: 3,
    obrasParalizadas: 2,
    accidentesReportados: 0,
    reclamosSalud: 2,
    pedidosSinRespuesta: 3,
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
]
